# Generated by Django 5.1.4 on 2024-12-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0004_rename_product_buy_record_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
