# Generated by Django 5.1.4 on 2024-12-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0005_product_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_record',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='buy_record',
            old_name='user_id',
            new_name='user',
        ),
    ]
