# Generated by Django 5.1.4 on 2024-12-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0006_rename_product_id_buy_record_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_record',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
