# Generated by Django 5.1.4 on 2025-01-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0007_buy_record_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='RentalRecord',
            fields=[
                ('order_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_price', models.IntegerField()),
                ('amount', models.IntegerField(default=1)),
                ('ren_time', models.IntegerField()),
                ('get_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('renting', 'Renting'), ('return', 'Return'), ('overdue', 'Overdue'), ('returned', 'Returned')], default='renting', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vfit.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_records', to='vfit.users')),
            ],
        ),
    ]
