# Generated by Django 5.1.4 on 2025-01-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0008_alter_users_full_name_rentalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrecord',
            name='overdue_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentalrecord',
            name='time_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
