# Generated by Django 5.1.4 on 2025-01-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0009_rentalrecord_overdue_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('renting', 'Renting'), ('return', 'Return'), ('overdue', 'Overdue'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('issue_description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=50)),
                ('rental_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vfit.rentalrecord')),
            ],
        ),
    ]
