# Generated by Django 5.1.4 on 2025-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0012_rename_contactinfo_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(default=13.736717),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(default=100.523186),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
