# Generated by Django 5.1.4 on 2025-02-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0013_contact_latitude_contact_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(default=15.117421421361927),
        ),
        migrations.AlterField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(default=104.90284046686651),
        ),
    ]
