# Generated by Django 5.1.4 on 2025-03-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0014_alter_contact_latitude_alter_contact_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='exercises/')),
                ('method', models.TextField()),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('sets', models.CharField(max_length=255)),
                ('muscle', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='buy_record',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
