# Generated by Django 5.1.4 on 2025-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0015_exercise_alter_buy_record_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
