# Generated by Django 5.1.4 on 2025-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0016_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issue_description',
            field=models.CharField(max_length=5000),
        ),
    ]
