# Generated by Django 5.1.4 on 2025-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfit', '0017_alter_report_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issue_description',
            field=models.TextField(),
        ),
    ]
